version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.15-browsers
    resource_class: small
    parallelism: 4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - browser-tools/install-chrome
      - run:
          name: Run tests
          command: |
            echo "Running tests"
            pwd
            echo $(npx nightwatch)
            FILES_JSON=$(npx nightwatch --list-files)
            echo "FILES_JSON=$FILES_JSON"
            ALL_TEST_FILES=$(echo $FILES_JSON | jq -r '.default | join("\n")')
            echo "ALL_TEST_FILES=$ALL_TEST_FILES"
            SPLIT_TEST_FILES=$(echo "$ALL_TEST_FILES" | circleci tests split)
            echo "SPLIT_TEST_FILES=$SPLIT_TEST_FILES"
            npm test $SPLIT_TEST_FILES

workflows:
  sample:
    jobs:
      - build-and-test
