version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.15-browsers
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - browser-tools/install-chrome
      - run:
          name: Run tests
          command: npm test

workflows:
  sample:
    jobs:
      - build-and-test
