version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  build:
    docker:
      - image: cimg/node:18.15-browsers
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

      - run: ls

      - run:
          name: Build
          command: npm run build

      - run: mkdir -p workspace
      - run: ls
      - run: ls ./dist

      - persist_to_workspace:
          root: ./workspace
          paths:
            - dist

  test:
    docker:
      - image: cimg/node:18.15-browsers
    resource_class: small
    parallelism: 4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

      - browser-tools/install-chrome

      - attach_workspace:
          at: ./workspace

      - run:
          name: Run tests
          command: |
            TEST_FILES_JSON=$(npx nightwatch --list-files)
            ALL_TEST_FILES=$(echo $TEST_FILES_JSON | jq -r '.default | join("\n")')
            PARTITION_TEST_FILES=$(echo "$ALL_TEST_FILES" | circleci tests split)
            npm test $PARTITION_TEST_FILES

workflows:
  sample:
    jobs:
      - build
      - test:
          requires:
            - build
